#!/bin/bash

# This script is designed for Arch Linux with systemd.
# Script created by Nicklas Rudolfsson n@rudolfsson.net

# Function to show a notification
show_notification() {
    local message="$1"
    notify-send "Notification" "$message" -t 3000
}

# Prompt user for confirmation
confirm_action() {
    local action="$1"
    local message="$2"
    local confirmation

    while true; do
        confirmation=$(echo -e "Yes\nNo" | dmenu -p "$message")
        case "$confirmation" in
            Yes)
                show_notification "$action"
                return 0
                ;;
            No)
                return 1
                ;;
            *)
                ;;
        esac
    done
}

# Main menu options
while true; do
    ACTION=$(echo -e "Suspend\nKill DWM\nLog out\nReboot\nShutdown\nExit script" | dmenu -p "Choose an action:")

    case "$ACTION" in
        Suspend)
            if confirm_action "The system is now suspending!" "Are you sure you want to suspend the system?"; then
                show_notification "The system is now suspending!"
                sleep 3
                systemctl suspend
                exit 0
            fi
            ;;
        Kill\ DWM)
            if confirm_action "DWM is now being killed!" "Are you sure you want to kill DWM?"; then
                sleep 3
                pkill dwm
            fi
            ;;
        Log\ out)
            if confirm_action "You are now being logged out!" "Are you sure you want to log out?"; then
                sleep 3
                pkill -KILL -u $USER
            fi
            ;;
        Reboot)
            if confirm_action "The system is now rebooting!" "Are you sure you want to reboot the system?"; then
                sleep 3
                systemctl reboot
            fi
            ;;
        Shutdown)
            if confirm_action "The system is now shutting down!" "Are you sure you want to shut down the system?"; then
                sleep 3
                systemctl poweroff
            fi
            ;;
        Exit\ script)
            exit 0
            ;;
        *)
            ;;
    esac
done
